/* Generated By:JJTree: Do not edit this line. ASTMath.java */

package com.bigdata.rdf.sail.sparql.ast;

import org.openrdf.query.algebra.MathExpr.MathOp;
import org.embergraph.rdf.sail.sparql.ast.SimpleNode;
import org.embergraph.rdf.sail.sparql.ast.SyntaxTreeBuilder;
import org.embergraph.rdf.sail.sparql.ast.SyntaxTreeBuilderVisitor;
import org.embergraph.rdf.sail.sparql.ast.VisitorException;

public class ASTMath extends SimpleNode {

	private MathOp operator;

	public ASTMath(int id) {
		super(id);
	}

	public ASTMath(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public MathOp getOperator() {
		return operator;
	}

	public void setOperator(MathOp operator) {
		this.operator = operator;
	}

	@Override
	public String toString()
	{
		return super.toString() + " (" + operator + ")";
	}
}
