/* Generated By:JJTree: Do not edit this line. ASTSelectQuery.java */

package com.bigdata.rdf.sail.sparql.ast;

import org.embergraph.rdf.sail.sparql.ast.ASTQuery;
import org.embergraph.rdf.sail.sparql.ast.ASTSelect;
import org.embergraph.rdf.sail.sparql.ast.SyntaxTreeBuilder;
import org.embergraph.rdf.sail.sparql.ast.SyntaxTreeBuilderVisitor;
import org.embergraph.rdf.sail.sparql.ast.VisitorException;

public class ASTSelectQuery extends ASTQuery {

    public ASTSelectQuery(int id) {
        super(id);
    }

    public ASTSelectQuery(SyntaxTreeBuilder p, int id) {
        super(p, id);
    }

    @Override
    public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
        throws VisitorException
    {
        return visitor.visit(this, data);
    }

    public ASTSelect getSelect() {
        return jjtGetChild(ASTSelect.class);
    }

    public boolean isSubSelect() {
        return ! (parent instanceof ASTQueryContainer);
    }
}
