/* Generated By:JJTree: Do not edit this line. ASTWhereClause.java */

package com.bigdata.rdf.sail.sparql.ast;

import org.embergraph.rdf.sail.sparql.ast.ASTGraphPatternGroup;
import org.embergraph.rdf.sail.sparql.ast.SimpleNode;
import org.embergraph.rdf.sail.sparql.ast.SyntaxTreeBuilder;
import org.embergraph.rdf.sail.sparql.ast.SyntaxTreeBuilderVisitor;
import org.embergraph.rdf.sail.sparql.ast.VisitorException;

public class ASTWhereClause extends SimpleNode {

	public ASTWhereClause(int id) {
		super(id);
	}

	public ASTWhereClause(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public ASTGraphPatternGroup getGraphPatternGroup() {
		return jjtGetChild(ASTGraphPatternGroup.class);
	}
}
