/* Generated By:JavaCC: Do not edit this line. SyntaxTreeBuilderTreeConstants.java Version 5.0 */
package org.embergraph.rdf.sail.sparql.ast;

public interface SyntaxTreeBuilderTreeConstants {
  int JJTUPDATESEQUENCE = 0;
  int JJTUPDATECONTAINER = 1;
  int JJTQUERYCONTAINER = 2;
  int JJTVOID = 3;
  int JJTBASEDECL = 4;
  int JJTPREFIXDECL = 5;
  int JJTSELECTQUERY = 6;
  int JJTSELECT = 7;
  int JJTPROJECTIONELEM = 8;
  int JJTCONSTRUCTQUERY = 9;
  int JJTCONSTRUCT = 10;
  int JJTDESCRIBEQUERY = 11;
  int JJTDESCRIBE = 12;
  int JJTASKQUERY = 13;
  int JJTNAMEDSUBQUERY = 14;
  int JJTDATASETCLAUSE = 15;
  int JJTWHERECLAUSE = 16;
  int JJTBINDINGSCLAUSE = 17;
  int JJTINLINEDATA = 18;
  int JJTBINDINGSET = 19;
  int JJTBINDINGVALUE = 20;
  int JJTGROUPCLAUSE = 21;
  int JJTORDERCLAUSE = 22;
  int JJTGROUPCONDITION = 23;
  int JJTHAVINGCLAUSE = 24;
  int JJTORDERCONDITION = 25;
  int JJTLIMIT = 26;
  int JJTOFFSET = 27;
  int JJTGRAPHPATTERNGROUP = 28;
  int JJTBASICGRAPHPATTERN = 29;
  int JJTNAMEDSUBQUERYINCLUDE = 30;
  int JJTOPTIONALGRAPHPATTERN = 31;
  int JJTGRAPHGRAPHPATTERN = 32;
  int JJTUNIONGRAPHPATTERN = 33;
  int JJTMINUSGRAPHPATTERN = 34;
  int JJTSERVICEGRAPHPATTERN = 35;
  int JJTCONSTRAINT = 36;
  int JJTFUNCTIONCALL = 37;
  int JJTTRIPLESSAMESUBJECT = 38;
  int JJTPROPERTYLIST = 39;
  int JJTOBJECTLIST = 40;
  int JJTTRIPLESSAMESUBJECTPATH = 41;
  int JJTPROPERTYLISTPATH = 42;
  int JJTPATHALTERNATIVE = 43;
  int JJTPATHSEQUENCE = 44;
  int JJTPATHELT = 45;
  int JJTIRI = 46;
  int JJTPATHONEINPROPERTYSET = 47;
  int JJTPATHMOD = 48;
  int JJTBLANKNODEPROPERTYLIST = 49;
  int JJTCOLLECTION = 50;
  int JJTVAR = 51;
  int JJTOR = 52;
  int JJTAND = 53;
  int JJTCOMPARE = 54;
  int JJTINFIX = 55;
  int JJTMATH = 56;
  int JJTNOT = 57;
  int JJTNUMERICLITERAL = 58;
  int JJTCOUNT = 59;
  int JJTSUM = 60;
  int JJTMIN = 61;
  int JJTMAX = 62;
  int JJTAVG = 63;
  int JJTSAMPLE = 64;
  int JJTGROUPCONCAT = 65;
  int JJTMD5 = 66;
  int JJTSHA1 = 67;
  int JJTSHA224 = 68;
  int JJTSHA256 = 69;
  int JJTSHA384 = 70;
  int JJTSHA512 = 71;
  int JJTNOW = 72;
  int JJTYEAR = 73;
  int JJTMONTH = 74;
  int JJTDAY = 75;
  int JJTHOURS = 76;
  int JJTMINUTES = 77;
  int JJTSECONDS = 78;
  int JJTTIMEZONE = 79;
  int JJTTZ = 80;
  int JJTRAND = 81;
  int JJTABS = 82;
  int JJTCEIL = 83;
  int JJTFLOOR = 84;
  int JJTROUND = 85;
  int JJTSUBSTR = 86;
  int JJTSTRLEN = 87;
  int JJTUPPERCASE = 88;
  int JJTLOWERCASE = 89;
  int JJTSTRSTARTS = 90;
  int JJTSTRENDS = 91;
  int JJTSTRBEFORE = 92;
  int JJTSTRAFTER = 93;
  int JJTREPLACE = 94;
  int JJTCONCAT = 95;
  int JJTCONTAINS = 96;
  int JJTENCODEFORURI = 97;
  int JJTIF = 98;
  int JJTIN = 99;
  int JJTNOTIN = 100;
  int JJTCOALESCE = 101;
  int JJTSTR = 102;
  int JJTLANG = 103;
  int JJTLANGMATCHES = 104;
  int JJTDATATYPE = 105;
  int JJTBOUND = 106;
  int JJTSAMETERM = 107;
  int JJTISIRI = 108;
  int JJTISBLANK = 109;
  int JJTISLITERAL = 110;
  int JJTISNUMERIC = 111;
  int JJTBNODEFUNC = 112;
  int JJTIRIFUNC = 113;
  int JJTSTRDT = 114;
  int JJTSTRLANG = 115;
  int JJTUUID = 116;
  int JJTSTRUUID = 117;
  int JJTBIND = 118;
  int JJTLET = 119;
  int JJTREGEXEXPRESSION = 120;
  int JJTEXISTSFUNC = 121;
  int JJTNOTEXISTSFUNC = 122;
  int JJTRDFLITERAL = 123;
  int JJTTRUE = 124;
  int JJTFALSE = 125;
  int JJTSTRING = 126;
  int JJTQNAME = 127;
  int JJTBLANKNODE = 128;
  int JJTGRAPHREFALL = 129;
  int JJTGRAPHORDEFAULT = 130;
  int JJTSOLUTIONSREF = 131;
  int JJTUNPARSEDQUADDATABLOCK = 132;
  int JJTQUADSNOTTRIPLES = 133;
  int JJTLOAD = 134;
  int JJTDROPENTAILMENTS = 135;
  int JJTCREATEENTAILMENTS = 136;
  int JJTENABLEENTAILMENTS = 137;
  int JJTDISABLEENTAILMENTS = 138;
  int JJTCLEAR = 139;
  int JJTDROP = 140;
  int JJTADD = 141;
  int JJTMOVE = 142;
  int JJTCOPY = 143;
  int JJTCREATE = 144;
  int JJTINSERTDATA = 145;
  int JJTDELETEDATA = 146;
  int JJTDELETEWHERE = 147;
  int JJTDELETECLAUSE = 148;
  int JJTINSERTCLAUSE = 149;
  int JJTMODIFY = 150;
  int JJTTREFPATTERN = 151;

  String[] jjtNodeName = {
    "UpdateSequence",
    "UpdateContainer",
    "QueryContainer",
    "void",
    "BaseDecl",
    "PrefixDecl",
    "SelectQuery",
    "Select",
    "ProjectionElem",
    "ConstructQuery",
    "Construct",
    "DescribeQuery",
    "Describe",
    "AskQuery",
    "NamedSubquery",
    "DatasetClause",
    "WhereClause",
    "BindingsClause",
    "InlineData",
    "BindingSet",
    "BindingValue",
    "GroupClause",
    "OrderClause",
    "GroupCondition",
    "HavingClause",
    "OrderCondition",
    "Limit",
    "Offset",
    "GraphPatternGroup",
    "BasicGraphPattern",
    "NamedSubqueryInclude",
    "OptionalGraphPattern",
    "GraphGraphPattern",
    "UnionGraphPattern",
    "MinusGraphPattern",
    "ServiceGraphPattern",
    "Constraint",
    "FunctionCall",
    "TriplesSameSubject",
    "PropertyList",
    "ObjectList",
    "TriplesSameSubjectPath",
    "PropertyListPath",
    "PathAlternative",
    "PathSequence",
    "PathElt",
    "IRI",
    "PathOneInPropertySet",
    "PathMod",
    "BlankNodePropertyList",
    "Collection",
    "Var",
    "Or",
    "And",
    "Compare",
    "Infix",
    "Math",
    "Not",
    "NumericLiteral",
    "Count",
    "Sum",
    "Min",
    "Max",
    "Avg",
    "Sample",
    "GroupConcat",
    "MD5",
    "SHA1",
    "SHA224",
    "SHA256",
    "SHA384",
    "SHA512",
    "Now",
    "Year",
    "Month",
    "Day",
    "Hours",
    "Minutes",
    "Seconds",
    "Timezone",
    "Tz",
    "Rand",
    "Abs",
    "Ceil",
    "Floor",
    "Round",
    "Substr",
    "StrLen",
    "UpperCase",
    "LowerCase",
    "StrStarts",
    "StrEnds",
    "StrBefore",
    "StrAfter",
    "Replace",
    "Concat",
    "Contains",
    "EncodeForURI",
    "If",
    "In",
    "NotIn",
    "Coalesce",
    "Str",
    "Lang",
    "LangMatches",
    "Datatype",
    "Bound",
    "SameTerm",
    "IsIRI",
    "IsBlank",
    "IsLiteral",
    "IsNumeric",
    "BNodeFunc",
    "IRIFunc",
    "StrDt",
    "StrLang",
    "UUID",
    "STRUUID",
    "Bind",
    "Let",
    "RegexExpression",
    "ExistsFunc",
    "NotExistsFunc",
    "RDFLiteral",
    "True",
    "False",
    "String",
    "QName",
    "BlankNode",
    "GraphRefAll",
    "GraphOrDefault",
    "SolutionsRef",
    "UnparsedQuadDataBlock",
    "QuadsNotTriples",
    "Load",
    "DropEntailments",
    "CreateEntailments",
    "EnableEntailments",
    "DisableEntailments",
    "Clear",
    "Drop",
    "Add",
    "Move",
    "Copy",
    "Create",
    "InsertData",
    "DeleteData",
    "DeleteWhere",
    "DeleteClause",
    "InsertClause",
    "Modify",
    "TRefPattern",
  };
}
/* JavaCC - OriginalChecksum=66824576798bd36c6450f4e65cc592d8 (do not edit this line) */
