/* Generated By:JJTree: Do not edit this line. ASTPathSequence.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bigdata.rdf.sail.sparql.ast;

import java.util.List;

import org.embergraph.rdf.sail.sparql.ast.ASTPathElt;
import org.embergraph.rdf.sail.sparql.ast.SimpleNode;
import org.embergraph.rdf.sail.sparql.ast.SyntaxTreeBuilder;
import org.embergraph.rdf.sail.sparql.ast.SyntaxTreeBuilderVisitor;
import org.embergraph.rdf.sail.sparql.ast.VisitorException;

public
class ASTPathSequence extends SimpleNode {
  public ASTPathSequence(int id) {
    super(id);
  }

  public ASTPathSequence(SyntaxTreeBuilder p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
    return visitor.visit(this, data);
  }
  
  public List<ASTPathElt> getPathElements() {
	  return jjtGetChildren(ASTPathElt.class);
  }
}
/* JavaCC - OriginalChecksum=291cd072e3d6ff6cb5758dc9b7f155ac (do not edit this line) */
