#!/bin/sh
set -e

[ -f /etc/default/embergraph ] && . /etc/default/embergraph

startEmbergraph() {
    service embergraph start || true
}

        [ -z "$BLZG_DATA" ] && BLZG_DATA=/var/lib/embergraph
        [ -z "$BLZG_CONF" ] && BLZG_CONF=/etc/embergraph
        [ -z "$JOURNAL" ] && JOURNAL="${BLZG_DATA}"/embergraph.jnl
        [ -z "$BLZG_USER" ] && BLZG_USER=blzg
        [ -z "$BLZG_GROUP" ] && BLZG_GROUP=blzg
        [ -z "$BLZG_LOG" ] && BLZG_LOG=/var/log/embergraph

        # Update the journal file location
        sed -i -e "s|com\\.bigdata\\.journal\\.AbstractJournal\\.file=.*|org.embergraph.journal.AbstractJournal.file=$JOURNAL|" \
        $BLZG_CONF/RWStore.properties

        # Update the rules.log location
        sed -i -e "s|log4j.appender.ruleLog.File=.*|log4j.appender.ruleLog.File=$BLZG_LOG/rules.log|" \
        $BLZG_CONF/log4j.properties

        touch $BLZG_LOG/rules.log
        chown $BLZG_USER:$BLZG_GROUP $BLZG_LOG/rules.log

        # if $2 is set, this is an upgrade
        if ( [ -n $2 ] && [ "$RESTART_ON_UPGRADE" != "false" ] ) ; then
            chkconfig embergraph on
            startEmbergraph
            # this is a fresh installation
        elif [ -z $2 ] ; then
            echo "### NOT starting embergraph after install, please execute"
            echo " sudo service embergraph start"
        fi
        # Change user name in config files that cannot read /etc/default/embergraph;
        # unfortunately we can do this only if /etc/default/embergraph is in place before installation
        sed -i -e "s/create 640 blzg blzg/create 640 $BLZG_USER $BLZG_GROUP/" /etc/logrotate.d/embergraph
